// Copyright (c) 2019, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: containerize-paketo
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2019-07-23
:page-description: Learn how to containerize and run your microservices with Open Liberty using Docker
:page-tags: ['Docker']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Containerizing and running Java microservices in Docker containers
:page-seo-description: A getting started tutorial with examples of how to containerize or dockerize your Java microservices by building a container image and running the image as a Docker container.
:guide-author: Open Liberty
= Containerizing microservices with Paketo Buildpacks and Docker

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the  https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to build your microservices with Paketo and Open Liberty while using Docker to containerize them.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You can easily deploy your microservices in different environments in a lightweight and portable manner by using containers. From development to production and across your DevOps environments, you can deploy your microservices consistently and efficiently with containers. You can run a container from a container image. Each container image is a package of what you need to run your microservice or application, from the code to its dependencies and configuration.

You'll learn how to build container images with Paketo buildpacks and run containers using Docker for your microservices. You'll specify the buildpacks and builder to be utilized by using the `pack build` command and run the image as Docker containers by using `docker run` command.

[another paragaph here explaining what paketo is a bit more.]

The two microservices that you'll be working with are called `system` and `inventory`. The `system` microservice returns the JVM system properties of the running container. The `inventory` microservice adds the properties from the `system` microservice to the inventory. This guide demonstrates how both microservices can built with Paketo, run and communicate with each other in different Docker containers. 

== Additional prerequisites

Before you begin, both Pack CLI and Docker need to be installed. For installation, refer to the https://buildpacks.io/docs/tools/pack/[offical Pack documentation^] and the https://docs.docker.com/get-docker/[official Docker documentation^]. You will build the container images with Pack CLI and run the image in Docker containers.

Make sure to start your Docker daemon before you proceed.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]


== Packaging your microservices

// static guide instructions:
ifndef::cloud-hosted[]
Navigate to the `start` directory to begin.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
To begin, run the following command to navigate to the **start** directory:
```bash
cd start
```
endif::[]

You can find the starting Java project in the `start` directory. This project is a multi-module Maven project that is made up of the `system` and `inventory` microservices. Each microservice is located in its own corresponding directory, `system` and `inventory`.

To try out the microservices by using Maven, run the following Maven goal to build the `system` microservice and run it inside Open Liberty:
[role='command']
```
mvn -pl system liberty:run
```

// static guide instructions:
ifndef::cloud-hosted[]
Open another command-line session and run the following Maven goal to build the `inventory` microservice and run it inside Open Liberty:
[role='command']
```
mvn -pl inventory liberty:run
```

After you see the following message in both command-line sessions, both of your services are ready:

[source, role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

To access the `inventory` service, which displays the current contents of the inventory, see http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^].

To access the `system` service, which shows the system properties of the running JVM, see http://localhost:9080/system/properties[^].

You can add the system properties of your localhost to the `inventory` service at http://localhost:9081/inventory/systems/localhost[http://localhost:9081/inventory/systems/localhost^].
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Select **Terminal** > **New Terminal** from the menu of the IDE to open another command-line session and run the following Maven goal to build the **inventory** microservice and run it inside Open Liberty:
```bash
cd /home/project/guide-containerize-paketo/start
mvn -pl inventory liberty:run
```

Select **Terminal** > **New Terminal** from the menu of the IDE to open a new command-line session. To access the **inventory** service, which displays the current contents of the inventory, run the following curl command: 
```bash
curl -s http://localhost:9081/inventory/systems | jq
```

After you see the following message in both command-line sessions, both of your services are ready:

```
The defaultServer server is ready to run a smarter planet.
```

The **system** service shows the system properties of the running JVM and can be found by running the following curl command:
```bash
curl -s http://localhost:9080/system/properties | jq
```

The system properties of your localhost can be added to the **inventory** service at **http://localhost:9081/inventory/systems/localhost**. Run the following curl command:
```bash
curl -s http://localhost:9081/inventory/systems/localhost | jq
```
endif::[]

// static guide instructions:
ifndef::cloud-hosted[]
After you are finished checking out the microservices, stop the Open Liberty servers by pressing `CTRL+C` in the command-line sessions where you ran the servers. Alternatively, you can run the `liberty:stop` goal in another command-line session:
[role='command']
```
mvn -pl system liberty:stop
mvn -pl inventory liberty:stop
```
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
After you are finished checking out the microservices, stop the Open Liberty servers by pressing **CTRL+C** in the command-line sessions where you ran the servers. Alternatively, you can run the **liberty:stop** goal in another command-line session from the 
**start** directory:
```bash
cd /home/project/guide-containerize/start
mvn -pl system liberty:stop
mvn -pl inventory liberty:stop
```
endif::[]

To package your microservices, run the Maven package goal to build the application `.war` files from the start directory so that the `.war` files are in the `system/target` and `inventory/target` directories.
[role='command']
```
mvn package
```

To learn more about RESTful web services and how to build them, see https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service. The `inventory` service is built in a similar way.

== Building the Container images with Paketo buildpacks

When building Docker images with the `docker build` command, you need a Dockerfile to instruct Docker on what you need inside of your final image. 

While Paketo uses buildpacks to create your images. Buildpacks are a set of executables that are able to inspect your source code, create a buil plan for it and exeute that build plan. Paketo features include building your source without a Dockerfile, advanced cacheing for fastter build times, minimal application images that only include what is used and a software bill-of-materials (SBOM) so you can inspect the image Paketo built for you.

Paketo Liberty buildpack provides the Open Liberty runtime to the builder orchestration to produce a Open Container Inivitiate (OCI) image that can run just about anywhere.

To begin, we must have Pack CLI installed and set your default builder to a `paketo-buildpacks` builder with the following command:
[role='command']
```
pack config default-builder gcr.io/paketo-buildpacks/builder:base
```

A Builder is comprised of several part which include the buildpacks, lifecycle and the stack. The buildpacks, as mentioned above, are the set of executables that will inspect your source code while the lifecycle is an orchestration that organizes the buildpacks and assembles the artifacts from the buildpacks in the final OCI image. Finally, the stack is comprised of two images being: the build image and the run image. The build image is the image used to create a devlopment environment for the lifecycle orchestration and the run image is the parent image that is going to be used for the final OCI image.

Next, construct your images with the following `pack build` command and the applicable flags to customize the build for the Open Liberty runtime:
[role='command']
```
pack build --path ./system \
--env BP_JAVA_APP_SERVER=liberty \
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" \
--env BP_LIBERTY_PROFILE=jakartaee9 \
--buildpack paketo-buildpacks/eclipse-openj9 \
--buildpack paketo-buildpacks/java system:1.0-SNAPSHOT

pack build --path ./inventory \
--env BP_JAVA_APP_SERVER=liberty \
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" \
--env BP_LIBERTY_PROFILE=jakartaee9 \
--buildpack paketo-buildpacks/eclipse-openj9 \
--buildpack paketo-buildpacks/java inventory:1.0-SNAPSHOT
```

The following table describes the flags and environment variables supplied to customize your Paketo buildpacks:
[cols="35, 100", options="header"]
|===
| *Flag*                  | *Description*
| --path                  | Relative path to your application source code.
| --buildpack             | Buildpack to be included in the OCI build process.
| --env                   | Enviornment variables for the `pack build` process.
| BP_JAVA_APP_SERVER      | The application server to use, in the case it's `Liberty`.
| BP_MAVEN_BUILT_ARTIFACT | Include the `server.xml` information from Maven into the `pack build` process.
| BP_LIBERTY_PROFILE      | The Liberty profile to use. Defaults to `full`.
|===

Learn more about Docker on the https://www.docker.com/what-docker[official Docker page^].

== Running your microservices in Docker containers
Now that your two images are built, you will run your microservices in Docker containers:

[role='command']
```
docker run --rm -d --name system -p 9080:9080 system:1.0-SNAPSHOT
docker run --rm -d --name inventory -p 9081:9081 inventory:1.0-SNAPSHOT
```

The following table describes the flags in these commands:

[cols="20, 100", options="header"]
|===
| *Flag* | *Description*
| --rm   | Removes the container when the container is stopped.
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the host ports to the container ports. For example: `-p <HOST_PORT>:<CONTAINER_PORT>`
|===

Next, run the `docker ps` command to verify that your containers are started:

[role='command']
```
docker ps
```

Make sure that your containers are running and show `Up` as their status:

[role="no_copy"]
----
CONTAINER ID    IMAGE                   COMMAND                  CREATED          STATUS          PORTS                                        NAMES
2b584282e0f5    inventory:1.0-SNAPSHOT  "/opt/ol/helpers/run…"   2 seconds ago    Up 1 second     9080/tcp, 9443/tcp, 0.0.0.0:9081->9081/tcp   inventory
99a98313705f    system:1.0-SNAPSHOT     "/opt/ol/helpers/run…"   3 seconds ago    Up 2 seconds    0.0.0.0:9080->9080/tcp, 9443/tcp             system
----

If a problem occurs and your containers exit prematurely, the containers don't appear in the container list that the `docker ps` command displays. Instead, your containers appear with an `Exited` status when they run the `docker ps -a` command. Run the `docker logs system` and `docker logs inventory` commands to view the container logs for any potential problems. Run the `docker stats system` and `docker stats inventory` commands to display a live stream of usage statistics for your containers. You can also double-check that your Dockerfiles are correct. When you find the cause of the issues, remove the faulty containers with the `docker rm system` and `docker rm inventory` commands. Rebuild your images, and start the containers again.

// static guide instructions:
ifndef::cloud-hosted[]
To access the application, go to the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL. An empty list is expected because no system properties are stored in the inventory yet. 
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
To access the application, run the following curl command. An empty list is expected because no system properties are stored in the inventory yet:
```bash
curl -s http://localhost:9081/inventory/systems | jq
```
endif::[]

Next, retrieve the `system` container's IP address by running the following:

[role='command']
```
docker inspect -f "{{.NetworkSettings.IPAddress }}" system
```

The command returns the system container IP address:

[role="no_copy"]
----
172.17.0.2
----

In this case, the IP address for the `system` service is `172.17.0.2`. Take note of this IP address to construct the URL to view the system properties. 

// static guide instructions:
ifndef::cloud-hosted[]
Go to the `\http://localhost:9081/inventory/systems/pass:c[[system-ip-address]]` URL by replacing `[system-ip-address]` with the IP address that you obtained earlier. You see a result in JSON format with the system properties of your local JVM. When you go to this URL, these system properties are automatically stored in the inventory. Go back to the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL and you see a new entry for `[system-ip-address]`.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Run the following commands to go to the **http://localhost:9081/inventory/systems/[system-ip-address]** by replacing **[system-ip-address]** URL with the IP address that you obtained earlier:
```bash
SYSTEM_IP=`docker inspect -f "{{.NetworkSettings.IPAddress }}" system`
curl -s http://localhost:9081/inventory/systems/{$SYSTEM_IP} | jq
```

You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system properties are automatically stored in the inventory. Run the following curl command and you see a new entry for **[system-ip-address]**:
```bash
curl -s http://localhost:9081/inventory/systems | jq
```
endif::[]

== Externalizing server configuration

// File 0
inventory/server.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/inventory/src/main/liberty/config/server.xml[]
----

As mentioned at the beginning of this guide, one of the advantages of using containers is that they are portable and can be moved and deployed efficiently across all of your DevOps environments. Configuration often changes across different environments, and by externalizing your server configuration, you can simplify the development process.

Imagine a scenario where you are developing an Open Liberty application on port `9081` but to deploy it to production, it must be available on port `9091`. To manage this scenario, you can keep two different versions of the `server.xml` file; one for production and one for development. However, trying to maintain two different versions of a file might lead to mistakes. A better solution would be to externalize the configuration of the port number and use the value of an environment variable that is stored in each environment. 

In this example, you will use an environment variable to externally configure the HTTP port number of the `inventory` service. 

In the [hotspot file=0]`inventory/server.xml` file, the [hotspot=httpPort file=0]`default.http.port` variable is declared and is used in the [hotspot=httpEndpoint file=0]`httpEndpoint` element to define the service endpoint. The default value of the [hotspot=httpPort file=0]`default.http.port` variable is `9081`. However, this value is only used if no other value is specified. You can replace this value in the container by using the -e flag for the podman run command. 

Run the following commands to stop and remove the `inventory` container and rerun it with the `default.http.port` environment variable set:

[role='command']
```
docker stop inventory
docker rm inventory 
docker run -d --name inventory -e default.http.port=9091 -p 9091:9091 inventory:1.0-SNAPSHOT
```

The `-e` flag can be used to create and set the values of environment variables in a Docker container. In this case, you are setting the `default.http.port` environment variable to `9091` for the `inventory` container.

Now, when the service is starting up, Open Liberty finds the `default.http.port` environment variable and uses it to set the value of the [hotspot=httpPort file=0]`default.http.port` variable to be used in the HTTP endpoint.

// static guide instructions:
ifndef::cloud-hosted[]
The `inventory` service is now available on the new port number that you specified. You can see the contents of the inventory at the http://localhost:9091/inventory/systems[http://localhost:9091/inventory/systems^] URL. You can add your local system properties at `\http://localhost:9091/inventory/systems/pass:c[[system-ip-address]]` by replacing `[system-ip-address]` with the IP address that you obtained in the previous section. The `system` service remains unchanged and is available at the http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
The **inventory** service is now available on the new port number that you specified. You can see the contents of the inventory at the **http://localhost:9091/inventory/systems** URL. Run the following curl command:
```bash
curl -s http://localhost:9091/inventory/systems | jq
```

You can add your local system properties at the **http://localhost:9091/inventory/systems/[system-ip-address]** URL by replacing **[system-ip-address]** with the IP address that you obtained in the previous section. Run the following commands:
```bash
SYSTEM_IP=`docker inspect -f "{{.NetworkSettings.IPAddress }}" system`
curl -s http://localhost:9091/inventory/systems/{$SYSTEM_IP} | jq
```

The **system** service remains unchanged and is available at the **http://localhost:9080/system/properties** URL. Run the following curl command:
```bash
curl -s http://localhost:9080/system/properties | jq
```
endif::[]

You can externalize the configuration of more than just the port numbers. To learn more about Open Liberty server configuration, check out the https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html[Server Configuration Overview^] docs. 

== Testing the microservices

You can test your microservices manually by hitting the endpoints or with automated tests that check your running Docker containers.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointIT` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java`
----

SystemEndpointIT.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java[]
----

The [hotspot=testGetProperties file=0]`testGetProperties()` method checks for a `200` response code from the `system` service endpoint.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryEndpointIT` class.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java`
----

InventoryEndpointIT.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java[]
----

* The [hotspot=testEmptyInventory file=1]`testEmptyInventory()` method checks that the `inventory` service has a total of 0 systems before anything is added to it.
* The [hotspot=testHostRegistration file=1]`testHostRegistration()` method checks that the `system` service was added to `inventory` properly.
* The [hotspot=testSystemPropertiesMatch file=1]`testSystemPropertiesMatch()` checks that the `system` properties match what was added into the `inventory` service.
* The [hotspot=testUnknownHost file=1]`testUnknownHost()` method checks that an error is raised if an unknown host name is being added into the `inventory` service.
* The [hotspot=systemServiceIp file=1]`systemServiceIp` variable has the same value as the IP address that you retrieved in the previous section when you manually added the `system` service into the `inventory` service. This value of the IP address is passed in when you run the tests.

=== Running the tests
// static guide instructions
ifndef::cloud-hosted[]
Run the Maven `package` goal to compile the test classes. Run the Maven `failsafe` goal to test the services that are running in the Docker containers by replacing the `[system-ip-address]` with the IP address that you determined previously.

[role='command']
```
mvn package
mvn failsafe:integration-test -Dsystem.ip=[system-ip-address] -Dinventory.http.port=9081 -Dsystem.http.port=9080
```
endif::[]

// cloud-hosted guide instructions
ifdef::cloud-hosted[]
Run the Maven **package** goal to compile the test classes. Run the Maven **failsafe** goal to test the services that are running in the Docker containers by setting **-Dsystem.ip** to the IP address that you determined previously.

```bash
SYSTEM_IP=`docker inspect -f "{{.NetworkSettings.IPAddress }}" system`
mvn package
mvn failsafe:integration-test -Dsystem.ip="$SYSTEM_IP" -Dinventory.http.port=9091 -Dsystem.http.port=9080
```
endif::[]

If the tests pass, you see output similar to the following example:

[role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.653 s - in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.935 s - in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

When you are finished with the services, run the following commands to stop and remove your containers:

[role='command']
```
docker stop inventory system 
docker rm inventory system
```


== Great work! You're done!

You have just built Docker images and run two microservices on Open Liberty in containers. 

include::{common-includes}/attribution.adoc[]
