// Copyright (c) 2019, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: paketo-buildpacks-intro
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2022-07-01
:page-description: Learn how to build your microservices with Paketo and Open Liberty and run them in a container manager.
:page-tags: ['Docker']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Building and containerizing microservices with Paketo Buildpacks 
:page-seo-description: A getting started tutorial with examples of how to build Open Container Initiative (OCI) images with Paketo Buildpacks and deploying them in popular container managers like Docker and Podman.  
:guide-author: Open Liberty
= Containerizing microservices with Paketo Buildpacks and Docker

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the  https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to build your microservices with Paketo and Open Liberty and run them in a container manager.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn

You can easily deploy your microservices in different environments in a lightweight and portable manner by using containers. From development to production and across your DevOps environments, you can deploy your microservices consistently and efficiently with containers. You can run a container from a container image. Each container image is a package of what you need to run your microservice or application, from the code to its dependencies and configuration.

You'll learn how to build your microservices into OCI images with `Paketo buildpacks` and run them with your preferred container manager, such as `Podman` or `Docker`. You'll specify the buildpacks and builder to be utilized in the `pack build` command to construct your microservice image.

The microservice that you'll be working with is called `system`. The `system` miroservice return the JVM system properties of the running container. This guide demonstrates how microservices can be built with `Paketo buildpacks` and run them with your preferred container manager.

== Additional prerequisites

Before starting the guide, ensure that you have installed the `Pack CLI` and a container manager such as `Podman` or `Docker`. For installation of the `Pack CLI`, refer to the https://buildpacks.io/docs/tools/pack/[offical Pack documentation^] and for installation of a container manager, refer to https://podman.io/getting-started/installation[Offical Podman Documentation^] or the https://docs.docker.com/get-docker/[official Docker documentation^].

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

== Packaging your microservices

// static guide instructions:
Navigate to the `start` directory to begin.

You can find the starting Java project in the `start` directory. This project contains a microservice called `system`, which can be found in the corresponding directory, `system`.

To try out the microservice by using Maven, run the following Maven goal to build the `system` microservice and run it inside Open Liberty:
[role='command']
----
mvn -pl system liberty:run
----

After you see the following message in the command-line session, your service is ready:

[source, role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

To access the `system` service, which shows the system properties of the running JVM, see http://localhost:9080/system/properties[^].

// static guide instructions:
After you are finished checking out the `system` service, stop the Open Liberty server by pressing `CTRL+C` in the command-line session where you ran the server. Alternatively, you can run hte `liberty:stop` goal in another command-line session:
[role='command']
----
mvn -pl system liberty:stop
----

To package your microservice, run the maven package goal to build the application `.war` files from the start directory so that the `.war` file is in the `system/target` directory.

[role='command']
----
mvn package
----

To learn more about RESTful web services and how to build them, see https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service. 

== Building images with Paketo buildpacks

Before attempting to build your image, ensure that you have installed https://buildpacks.io/docs/tools/pack/[Pack CLI]. The `Pack CLI` tool facilitates the use of buildpacks and provides functionality to build and rebase images with buildpacks.

`Paketo buildpacks` is an open source project which provides users with production-ready buildpacks for the most popular languages and framworks, including the Open Liberty server. A `buildpack` is a set of executables that inspects and transforms your application source code into Open Containers Initiative (OCI) images that can be ran in nearly any container manager.

When a `buildpack` is executed, there are two phases that occur, the `detect` phase and the `build` phase. The `detect` phase checks against your application source code to ensure the buildpack is applicable. If applicable, the `build` phase will run which downloads all of the application dependencies, compile your source code and constructs a container image for your application.

The benefits of using `Paketo Buildpacks` with the `Pack CLI` to build your application compared to other traditional build tools, include:

* Generating your application images without a Containerfile or Dockerfile.
* Advanced image cacheing for faster rebuild times of your application.
* Generate a software bill-of-materials (SBOM) which provides information on the contents of your final image.
* Optimizing image size for minimal final application image.
* Auto-detection and installation of your app's dependencies directly from it's source code.
* Patching OS-level vulnerabilites in your images automatically upon rebuilding.

Set your `pack` default builder to the `Paketo Buildpacks` builder with the following command:
[role='command']
```
pack config default-builder gcr.io/paketo-buildpacks/builder:base
```

A `builder` in the buildpack ecosystem, is an image comprised of three parts:

* A set of buildpacks that apply your application's dependencies.
* A stack, which provides the OS layer for your appliation image.
* A lifecycle which analyzes, detects and assembles your final application image.

The default builder is the base builder used by all other commands that are run with the `Pack CLI`, in this instance we set this to the `Paketo Buildpacks` builder to use the features it offers.

Now, to begin constructing your `system` service image, run the following `pack build` command with the applicable flags and environment variables to customize your Open Liberty image:

[.tab_link.podman_link]
`*PODMAN*`
[.tab_link.docker_link]
`*DOCKER*`

[.tab_content.docker_section]
--

[role='command']
----
pack build --path ./system --env BP_JAVA_APP_SERVER=liberty --env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" --env BP_LIBERTY_PROFILE=jakartaee9 --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java system:1.0-SNAPSHOT
----
--

[.tab_content.podman_section]
--

Currently, `Pack CLI` does not officially support building images for `Podman` on Windows, so for the time being, you are limited to using `Docker` exclusively.

[role='command']
----
pack build --path ./system --env BP_JAVA_APP_SERVER=liberty --env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" --env BP_LIBERTY_PROFILE=jakartaee9 --buildpack paketo-buildpacks/eclipse-openj9 --buildpack paketo-buildpacks/java --docker-host=inherit --trust-builder=true system:1.0-SNAPSHOT
----

If you would like to try building your images for `Podman` but have your `Pack CLI` configured for `Docker`, then refer to the https://buildpacks.io/docs/app-developer-guide/building-on-podman/#usage[Build with Podman^] page in the `Pack CLI` documentation.

--

The following table describes the flags supplied to customize your Open Liberty image:
[cols="35, 100", options="header"]
|===
| *Flag*                  | *Description*
| --path                  | Relative path to your application source code.
| --buildpack             | Buildpack to be included in the OCI build process.
| --env                   | Enviornment variables for the `pack build` process.
| --docker-host           | Address to docker daemon that will be exposed to build container. Use `inherit` value when the docker daemon address is set to the DOCKER_HOST environment variable.
| --trust-builder         | Trust the provided builder.
|===

For more information and to dive deeper on all supported flags, view the https://buildpacks.io/docs/tools/pack/cli/pack_build/[pack build command Documentation^]. 

The following table describes the environment variables supplied for your application image. 
[cols="35, 100", options="header"] 
|===
| *Enviornment Variables* | *Description*
| BP_JAVA_APP_SERVER      | The application server to use.
| BP_MAVEN_BUILT_ARTIFACT | Include the `server.xml` and the `.war` file from the Maven process into the `pack build` process.
| BP_LIBERTY_PROFILE      | The Liberty profile to use. Defaults to `full`.
|===


Explore all of the flags, variables and options available for the Paketo Liberty buildpack on the https://github.com/paketo-buildpacks/liberty[Paketo Liberty page^]. 

== Running your microservices in containers

Now that your `system` image is built, you will now run your microservice in a container. Since the final images that are generated from `Pack CLI` are Open Containers Initiative (OCI) images, they are compatible with which container manager you have configured with `Pack CLI`.

[.tab_link.podman_link]
`*PODMAN*`
[.tab_link.docker_link]
`*DOCKER*`

[.tab_content.podman_section]
--
[role='command']
----
podman run --rm -d --name system -p 9080:9080 system:1.0-SNAPSHOT 
----
--

[.tab_content.docker_section]
--
[role='command']
----
docker run --rm -d --name system -p 9080:9080 system:1.0-SNAPSHOT 
----
--

The following table describes the flags in these commands:

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| --rm   | Removes the container when the container is stopped.
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the host ports to the container ports. For example: `-p <HOST_PORT>:<CONTAINER_PORT>`
|===

Next, run the following command to verify that your container has been started:

[.tab_link.podman_link]
`*PODMAN*`
[.tab_link.docker_link]
`*DOCKER*`

[.tab_content.podman_section]
--
[role='command']
----
podman ps
----
--

[.tab_content.docker_section]
--
[role='command']
----
docker ps
----
--

Make sure that your containers are running and show `Up` as their status:

[role="no_copy"]
----
CONTAINER ID    IMAGE                   COMMAND                  CREATED          STATUS          PORTS                                        NAMES
99a98313705f    system:1.0-SNAPSHOT     "/opt/ol/helpers/run…"   3 seconds ago    Up 2 seconds    0.0.0.0:9080->9080/tcp, 9443/tcp             system
----

If a problem occurs and your containers exit prematurely, the containers don't appear in the container list that the `docker ps` command displays. Instead, your container appear with an `Exited` status when they run the `docker ps -a` command. Run the `docker logs system` command to view the container logs for any potential problems. Run the `docker stats system` commands to display a live stream of usage statistics for your container. When you find the cause of the issues, remove the faulty container with the `docker rm system` command. Rebuild your image, and start the container again.

// static guide instructions:
To acces the `system` service, which shows the system properties of the running JVM, see `http://localhost:9080/system/properties`

After you have verifyied that your `system` service is up and running in your contiainer, you are able to stop and remove your container with the following command:

[.tab_link.podman_link]
`*PODMAN*`
[.tab_link.docker_link]
`*DOCKER*`

[.tab_content.podman_section]
--
[role='command']
----
podman stop system
----
--

[.tab_content.docker_section]
--
[role='command']
----
docker stop system
----
--

== Great work! You're done!

You have just built Docker images and run two microservices on Open Liberty in containers. 

include::{common-includes}/attribution.adoc[]
